import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./components/SessionProvider";
import Navbar from "./components/Navbar";
import { auth } from "../app/libs/auth";
import { Noto_Sans_Thai } from "next/font/google";

const Noto_sans = Noto_Sans_Thai({
  style: ["normal"],
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={Noto_sans.className}>
        <AuthProvider session={session} key={session?.expires}>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
